### ISSUE TITLE
Mediawiki MultimediaViewer and Gadget extension conflicts

### ISSUE THREAD

**Issue by pilhokim** [mediawiki4intranet/configs#2]
We have been using [MultimediaViewer ](https://www.mediawiki.org/wiki/Extension:MultimediaViewer) gives a great user experience with pretty image slideshows. Unfortunately MultimediaViewer does not work with Mediawiki4Intranet after installation. For details, please see the process that I have used.

Firstly, a part of my LocalSettings.php related with MultimediaViewer extension:
```php
<?php

require_once 'configs/ServerSettings.php'; # use this under UNIX, or BaseSettings.php under Windows

wfLoadExtension('Gadgets');
wfLoadExtension('BetaFeatures');
wfLoadExtension('CommonsMetadata');
wfLoadExtension('MultimediaViewer');

$wgMediaViewerIsInBeta = true;
$wgMediaViewerEnableByDefault = true;
$wgMediaViewerEnableByDefaultForAnonymous = true;
```

Gadgets, BetaFeatures, CommonsMetaData are required extensions for MultimediaViewer.

I tried several combinations disabling each extensions one-by-one and found Gadgets must be disabled. I found that enabling [Gadgets](https://www.mediawiki.org/wiki/Extension:Gadgets) disables intraACL editor's user interaction. For instance in the user selection box, it does not suggest a matching user name. Also selecting All button in the intraACL editor shows no effect on other check buttons (Usually it should automatically select other rights). 

Would it be feasible to use MultimediaViewer and Gadget with Mediawiki4Intranet?

**Comment by vitalif** [comment]
See https://github.com/mediawiki4intranet/IntraACL/issues/56
This may be a bug of Gadgets extension.
Check if there is a line `$wgResourceModules = array(` and if it's there change it to `$wgResourceModules += array(`

**Comment by pilhokim** [comment]
You were right :+1: I narrowed down the problem and the issue looks  not related with mediawiki4intranet but with [MediaWiki:GallerySlideshow.js](https://commons.wikimedia.org/wiki/MediaWiki:GallerySlideshow.js) and MediaWiki:Gadgets-definition. Thank you a lot for the advice. Let me close this issue.
